ALTER TABLE events
  ADD COLUMN try_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ADD COLUMN ai_summary TEXT;

ALTER TABLE rules
  ADD COLUMN ai_enabled BOOLEAN NOT NULL DEFAULT false;
